[package]
name = "controller"
version = "0.1.5"
edition = "2018"
publish = ["artifactory"]

[dependencies]
domain = { path = "../domain" , version = "0.1.5"}
tokio-postgres = "0.7.2"
db-postgres = { path = "../db-postgres", version = "0.1.5" }