[package]
name = "presenter"
version = "0.1.5"
edition = "2018"

[dependencies]
domain = { path = "../domain" }
tokio = { version = "1.6.0", features = ["full"] }
rusoto_lambda = "0.47.0"
bytes = "1.1.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
