name: Deploy TF skipping Test

on:
  push:
    branches:
      - update-tf

jobs:

  push_dev:
    if: github.ref == 'refs/heads/update-tf'
    runs-on: ubuntu-latest
    env:
      TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Terraform Config 
        run: |
          chmod +x ./scripts/terraform-enterprise-push.sh
          ./scripts/terraform-enterprise-push.sh lambda/terraform HocVienCongGiao/dev-sg-lambda-services-hvcg-example-service
